apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
  namespace: db
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg==  # Administrator
  password: cGFzc3dvcmQ=          # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
  namespace: db
spec:
  memoryQuota: 128Mi
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
  namespace: db
spec:
  image: couchbase/server:6.6.2  
  security:
    adminSecret: cb-example-auth
  networking:
    exposeAdminConsole: true
    adminConsoleServices:
    - data
  buckets:
    managed: true
  servers:
  - size: 3  
    name: all_services
    services:
    - data
    - index
    - query
    - search
  volumeClaimTemplates: 
  - metadata:
      name: couchbase 
    spec:
      storageClassName: local-path
      resources: 
        requests:
          storage: 1Gi
